<?php
$strings = array(
	'page_title' => __( 'Windows Azure Simple Upload Plugin Settings', 'windows-azure-simple-upload' ),
	'menu_title' => __( 'Windows Azure Simple Upload', 'windows-azure-simple-upload' ),
	'title' => __( 'Windows Azure Simple Upload Plugin Settings', 'windows-azure-simple-upload' ),
	'description' => __( 'This WordPress plugin allows you to use Windows Azure Storage Service to host your media for your WordPress powered blog. Windows Azure provides storage in the cloud with authenticated access and triple replication to help keep your data safe. Applications work with data using REST conventions and standard HTTP operations to identify and expose data using URIs. This plugin allows you to easily upload, retrieve, and link to files stored on Windows Azure Storage service from within WordPress.' ),
	'register' => __( 'If you do not have Windows Azure Storage Account, please register for Windows Azure Services.' ),
	'azure_storage_account_name' => __( 'Store Account Name' ),
	'azure_storage_account_name_title' => __( 'Windows Azure Storage Account Name' ),
	'azure_storage_account_primary_access_key' => __( 'Store Account Key' ),
	'azure_storage_account_primary_access_key_title' => __( 'Windows Azure Storage Account Primary Access Key' ),
	'default_azure_storage_account_container_name' => __( 'Default Storage Container' ),
	'default_azure_storage_account_container_name_title' => __( 'Default container to be used for storing media files' ),
	'cname' => __( 'CNAME' ),
	'cname_title' => __( 'Use CNAME instead of Windows Azure Blob URL' ),
	'cname_description' => __( 'Note: Use this option if you would like to display image URLs belonging to your domain like' ),
	'cname_description2' => __( 'instead of' ),
	'cname_description3' => __( 'This CNAME must start with' ),
	'cname_description4' => __( 'and the administrator will have to update' ),
	'cname_description5' => __( 'Domain Name System' ),
	'cname_description6' => __( 'entries accordingly' ),
	'azure_storage_use_for_default_upload' => __( 'Use Windows Azure Storage for default upload' ),
	'azure_storage_use_for_default_upload_label' => __( 'Use Windows Azure Storage when uploading via WordPress upload tab.' ),
	'azure_storage_use_for_default_upload_small' => __( 'Note: Uncheck this to revert back to using your own web host for storage at anytime.' ),
	'azure_storage_keep_local_file' => __( 'Keep local files' ),
	'azure_storage_keep_local_file_title' => __( 'Do not delete local files after uploading them to Azure Storage.' ),
	'azure_storage_keep_local_file_label' => __( 'Keep local files after uploading them to Azure Storage.' ),
	'submit' => __( 'Save Changes' ),
	'save' => __( 'Saved settings.'),
	'dismiss' => __( 'Dismiss this warning.'),
	'newcontainer' => __( 'New container name:' ),
	'create_newcontainer' => __( 'Create New Container' ),
	'create_link' => __( 'Or create a new container by clicking here.' ),
	'save_container' => __( 'New container created!' )

);